# Generated by Django 5.2.7 on 2025-12-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_userfollow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.CharField(choices=[('bscs', 'Bachelor of Science in Computer Science'), ('bsit', 'Bachelor of Science in Information Technology'), ('bsis', 'Bachelor of Science in Information Systems'), ('bsce', 'Bachelor of Science in Civil Engineering'), ('bsee', 'Bachelor of Science in Electrical Engineering'), ('bsece', 'Bachelor of Science in Electronics and Engineering'), ('bscpe', 'Bachelor of Science in Computer Engineering'), ('bet', 'Bachelor of Engineering Technology'), ('baet', 'Bachelor of Automotive Engineering Technology'), ('beet', 'Bachelor of Electrical Engineering Technology'), ('bexet', 'Bachelor of Electronics Engineering Technology'), ('bmet', 'Bachelor of Mechanical Engineering Technology'), ('bmet-mt', 'BMET - Mechanical Technology'), ('bmet-ract', 'BMET - Refrigeration and Air-conditioning Technology'), ('bmet-waft', 'BMET - Welding and Fabrication Technology'), ('bit', 'Bachelor in Industrial Technology '), ('bit-adt', 'Architectural Drafting'), ('bit-at', 'Automotive Technology'), ('bit-elt', 'Electrical Technology'), ('bit-elex', 'Electronics Technology'), ('bit-mt', 'Mechanical Technology'), ('bit-hvacr', 'Heating, Ventilating & Air-Conditioning technology'), ('bit-waft', 'Welding & Fabrication Technology'), ('bshm', 'Bachelor of Science in Hospitality Management'), ('bsmt', 'Bachelor of Science in Tourism Management'), ('bsm', 'Bachelor of Science in Mathematics'), ('bses', 'Bachelor of Science in Environmental Science'), ('bael', 'Bachelor of Arts in English Language'), ('beed', 'Bachelor of Elementary Education'), ('bsed', 'Bachelor of Secondary Education'), ('bped', 'Bachelor of Physical Education'), ('btvted', 'Bachelor of Technical-Vocational Teacher Education')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('ccis', 'College of Computing and Information Sciences'), ('coe', 'College of Engineering'), ('cbt', 'College of Business and Technology'), ('cas', 'College of Arts and Sciences'), ('cte', 'College of Teacher Education')], max_length=50),
        ),
    ]
