# Generated by Django 5.2.7 on 2025-11-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_threadcomment_threadlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadpost',
            name='thread_type',
            field=models.CharField(choices=[('general', 'General'), ('discussion', 'Discussion'), ('question', 'Question'), ('guide', 'Guide'), ('announcement', 'Announcement'), ('accomplishment', 'Accomplishment')], default='General', max_length=50),
        ),
    ]
