# Generated by Django 5.2.7 on 2025-12-13 13:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_threadpost_thread_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadpost',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='thread_image'),
        ),
    ]
